name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install subversion g++ zlib1g-dev build-essential git python python3
          sudo apt-get -y install libncurses5-dev gawk gettext unzip file libssl-dev wget
          sudo apt-get -y install libelf-dev ecj fastjar java-propose-classpath
          sudo apt-get -y install build-essential libncursesw5-dev python unzip
          sudo apt-get -y install ncurses-dev ccache
          ccache -F 0
          ccache -M 0

      - name: Cache staging_dir
        uses: actions/cache@preview
        with:
          path: staging_dir
          key: staging_dir
          restore-keys: staging_dir

      - name: Cache ccache
        uses: actions/cache@preview
        with:
          path: ~/.ccache
          key: ccache
          restore-keys: ccache

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: make defconfig
        run: make defconfig

      - name: make download
        run: make -j4 V=w download

      - name: make
        run: make -j4 V=w

      - name: Finish
        run: |
          cat bin/targets/ramips/rt3883/sha256sums
          ls -lh bin/targets/ramips/rt3883/openwrt-ramips-rt3883-rt-n56u-squashfs-sysupgrade.bin
