name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install subversion g++ zlib1g-dev build-essential git python python3 \
            libncurses5-dev gawk gettext unzip file libssl-dev wget \
            libelf-dev ecj fastjar java-propose-classpath \
            build-essential libncursesw5-dev python unzip \
            ccache
          ccache -F 0
          ccache -M 0

      - name: Cache staging_dir
        uses: actions/cache@v1
        with:
          path: staging_dir
          key: staging_dir-${{ hashFiles(format('{0}{1}', github.workspace, '/.config')) }}
          restore-keys: staging_dir-

      - name: Cache ccache
        uses: actions/cache@v1
        with:
          path: ~/.ccache
          key: ccache-${{ hashFiles(format('{0}{1}', github.workspace, '/.config')) }}
          restore-keys: ccache-

      - name: Cache dl
        uses: actions/cache@v1
        with:
          path: dl
          key: dl-${{ hashFiles(format('{0}{1}', github.workspace, '/.config')) }}
          restore-keys: dl-

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: make defconfig
        run: make defconfig

      - name: make download
        run: make -j4 V=w download
        
      - name: make tools
        run: make -j4 V=w tools/compile && make -j4 V=w toolchain/compile

      - name: make
        if: startsWith(github.ref, 'refs/tags/')
        run: make -j4 V=w
        
      - name: Finish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cat bin/targets/ramips/rt3883/sha256sums
          ls -lh bin/targets/ramips/rt3883/openwrt-ramips-rt3883-asus_rt-n56u-squashfs-sysupgrade.bin

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/targets/ramips/rt3883/sha256sums
            bin/targets/ramips/rt3883/openwrt-ramips-rt3883-asus_rt-n56u-squashfs-sysupgrade.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
